-- Run once in Supabase SQL Editor if production does not execute Laravel migrations.
-- CampFix imports all users immediately, then sends each welcome email once in
-- a daily Brevo-sized batch.

create table if not exists public.welcome_email_deliveries (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    encrypted_password text,
    status varchar(30) not null default 'pending',
    attempts smallint not null default 0,
    next_attempt_at timestamp(0) without time zone,
    last_attempted_at timestamp(0) without time zone,
    claimed_at timestamp(0) without time zone,
    sent_at timestamp(0) without time zone,
    last_error text,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);

create unique index if not exists welcome_email_deliveries_user_id_unique
    on public.welcome_email_deliveries (user_id);
create index if not exists welcome_email_deliveries_status_index
    on public.welcome_email_deliveries (status);
create index if not exists welcome_email_deliveries_next_attempt_at_index
    on public.welcome_email_deliveries (next_attempt_at);
create index if not exists welcome_email_deliveries_last_attempted_at_index
    on public.welcome_email_deliveries (last_attempted_at);
create index if not exists welcome_email_deliveries_sent_at_index
    on public.welcome_email_deliveries (sent_at);
