-- Run this entire script once in Supabase Dashboard -> SQL Editor.
-- Event approval chains are configured by Intended User + Request Type.

create table if not exists public.event_request_types (
    id bigint generated by default as identity primary key,
    name varchar(255) not null unique,
    requires_department boolean not null default false,
    approval_roles jsonb,
    is_active boolean not null default true,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);

create table if not exists public.event_intended_users (
    id bigint generated by default as identity primary key,
    name varchar(255) not null unique,
    code varchar(255) not null unique,
    approval_roles jsonb,
    is_active boolean not null default true,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);

create table if not exists public.event_departments (
    id bigint generated by default as identity primary key,
    name varchar(255) not null unique,
    is_active boolean not null default true,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);

alter table public.event_requests add column if not exists approval_route jsonb;
alter table public.event_requests add column if not exists intended_user varchar(100);
alter table public.event_intended_users add column if not exists approval_roles jsonb;

insert into public.event_request_types (name, requires_department, approval_roles, is_active, created_at, updated_at)
values
    ('Academic', true, '["program_head", "academic_head", "building_admin", "school_admin"]'::jsonb, true, now(), now()),
    ('Non-Academic', false, '["building_admin", "school_admin"]'::jsonb, true, now(), now())
on conflict (name) do nothing;

insert into public.event_intended_users (name, code, is_active, created_at, updated_at)
values
    ('Faculty', 'faculty', true, now(), now()),
    ('Tertiary', 'tertiary', true, now(), now()),
    ('Senior High School', 'shs', true, now(), now()),
    ('Staff', 'staff', true, now(), now()),
    ('Maintenance', 'maintenance', true, now(), now())
on conflict (name) do nothing;

insert into public.event_departments (name, is_active, created_at, updated_at)
values
    ('GE', true, now(), now()),
    ('ICT', true, now(), now()),
    ('Business Management', true, now(), now()),
    ('THM', true, now(), now())
on conflict (name) do nothing;

-- Convert any education levels created by the previous version into intended users.
do $$
begin
    if to_regclass('public.event_education_levels') is not null then
        execute '
            insert into public.event_intended_users (name, code, is_active, created_at, updated_at)
            select levels.name, levels.code, levels.is_active, now(), now()
            from public.event_education_levels levels
            where not exists (
                select 1 from public.event_intended_users users
                where users.code = levels.code or users.name = levels.name
            )';
    end if;
end $$;

create table if not exists public.event_approval_chains (
    id bigint generated by default as identity primary key,
    event_intended_user_id bigint references public.event_intended_users(id) on delete cascade,
    event_request_type_id bigint not null references public.event_request_types(id) on delete cascade,
    approval_roles jsonb not null,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);

alter table public.event_approval_chains
    add column if not exists event_intended_user_id bigint references public.event_intended_users(id) on delete cascade;

-- Preserve old approval chains by mapping their education-level code to an intended user.
do $$
begin
    if to_regclass('public.event_education_levels') is not null
       and exists (
           select 1 from information_schema.columns
           where table_schema = 'public'
             and table_name = 'event_approval_chains'
             and column_name = 'event_education_level_id'
       ) then
        execute '
            update public.event_approval_chains chains
            set event_intended_user_id = users.id
            from public.event_education_levels levels
            join public.event_intended_users users on users.code = levels.code
            where chains.event_education_level_id = levels.id
              and chains.event_intended_user_id is null';
    end if;
end $$;

-- The old education-level relation is no longer used.
alter table public.event_approval_chains drop column if exists event_education_level_id cascade;
drop table if exists public.event_education_levels cascade;

delete from public.event_approval_chains where event_intended_user_id is null;
alter table public.event_approval_chains alter column event_intended_user_id set not null;

create unique index if not exists event_approval_chain_intended_type_unique
    on public.event_approval_chains (event_intended_user_id, event_request_type_id);

-- Preserve audience values for old requests. education_level remains an internal
-- compatibility column; it is no longer displayed or selected in the form.
update public.event_requests
set intended_user = education_level
where intended_user is null;

update public.event_requests
set intended_user = case
    when intended_user = 'shs' then 'shs'
    when intended_user is null or intended_user = '' then 'tertiary'
    else intended_user
end;

update public.event_requests
set education_level = case when intended_user = 'shs' then 'shs' else 'tertiary' end;

-- Seed every Intended User + Request Type combination.
insert into public.event_approval_chains
    (event_intended_user_id, event_request_type_id, approval_roles, created_at, updated_at)
select
    users.id,
    types.id,
    case
        when users.code = 'shs' then '["principal_assistant", "academic_head", "school_admin"]'::jsonb
        when types.name = 'Academic' then '["program_head", "academic_head", "building_admin", "school_admin"]'::jsonb
        else '["building_admin", "school_admin"]'::jsonb
    end,
    now(),
    now()
from public.event_intended_users users
cross join public.event_request_types types
where users.is_active = true and types.is_active = true
on conflict (event_intended_user_id, event_request_type_id)
do nothing;
