-- Run this once in Supabase Dashboard → SQL Editor for the CampFix database.
-- It creates the configurable Event Setup records used by Management → Event Requests.

create table if not exists public.event_request_types (
    id bigint generated by default as identity primary key,
    name varchar(255) not null unique,
    requires_department boolean not null default false,
    approval_roles jsonb,
    is_active boolean not null default true,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);

create table if not exists public.event_intended_users (
    id bigint generated by default as identity primary key,
    name varchar(255) not null unique,
    code varchar(255) not null unique,
    approval_roles jsonb,
    is_active boolean not null default true,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);

create table if not exists public.event_departments (
    id bigint generated by default as identity primary key,
    name varchar(255) not null unique,
    is_active boolean not null default true,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);

alter table public.event_requests
    add column if not exists approval_route jsonb;

alter table public.event_intended_users
    add column if not exists approval_roles jsonb;

insert into public.event_request_types (name, requires_department, approval_roles, is_active, created_at, updated_at)
values
    ('Academic', true, '["program_head", "academic_head", "building_admin", "school_admin"]'::jsonb, true, now(), now()),
    ('Non-Academic', false, '["building_admin", "school_admin"]'::jsonb, true, now(), now())
on conflict (name) do nothing;

-- Preserve the existing SHS workflow: SHS Principal → Academic Head → School Administrator.
update public.event_intended_users
set approval_roles = '["principal_assistant", "academic_head", "school_admin"]'::jsonb,
    updated_at = now()
where code = 'shs' and approval_roles is null;

insert into public.event_intended_users (name, code, is_active, created_at, updated_at)
values
    ('Faculty', 'faculty', true, now(), now()),
    ('Tertiary', 'tertiary', true, now(), now()),
    ('Senior High School', 'shs', true, now(), now()),
    ('Staff', 'staff', true, now(), now()),
    ('Maintenance', 'maintenance', true, now(), now())
on conflict (name) do nothing;

insert into public.event_departments (name, is_active, created_at, updated_at)
values
    ('GE', true, now(), now()),
    ('ICT', true, now(), now()),
    ('Business Management', true, now(), now()),
    ('THM', true, now(), now())
on conflict (name) do nothing;
