@extends('layouts.app')

@section('page_title')
<div><h2 class="mb-0"><i class="fas fa-chart-line me-2"></i>{{ $pageTitle }}</h2><p class="text-muted mb-0">{{ $pageSubtitle }}</p></div>
@endsection

@section('styles')
<style>
    .role-analytics{--blue:#1769e0;--green:#148a58;--red:#d93645;--amber:#e99a00;--ink:#10233f;--muted:#66758a;--border:#dce2ea;display:grid;gap:18px;min-height:calc(100vh - 92px);padding:20px;background:#f5f7fa}.ra-panel{border:1px solid var(--border);border-radius:8px;background:#fff;box-shadow:0 2px 7px rgba(16,35,63,.05)}
    .ra-filter{display:flex;flex-wrap:wrap;align-items:end;gap:12px;padding:16px}.ra-filter label{display:block;margin-bottom:5px;color:#45566d;font-size:12px;font-weight:700}.ra-filter .form-control,.ra-filter .btn{height:42px;border-radius:6px}.ra-filter .form-control{min-width:180px}
    .ra-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.ra-kpi{position:relative;min-height:126px;padding:18px 20px;overflow:hidden}.ra-kpi::before{position:absolute;inset:0 auto 0 0;width:5px;background:var(--accent);content:''}.ra-kpi-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.ra-kpi-label{color:var(--muted);font-size:12px;font-weight:800;text-transform:uppercase}.ra-kpi-icon{display:grid;width:38px;height:38px;place-items:center;border-radius:50%;color:var(--accent);background:#f2f6fb}.ra-kpi-value{margin-top:8px;color:var(--ink);font-size:30px;font-weight:800;line-height:1}.ra-kpi-context{margin-top:7px;color:#6c7c91;font-size:12px}
    .ra-header{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:17px 20px;border-bottom:1px solid #e5e9ef}.ra-header h3{margin:0;color:var(--ink);font-size:17px;font-weight:700}.ra-header p{margin:3px 0 0;color:var(--muted);font-size:12px}.ra-header-tools{display:flex;flex-wrap:wrap;align-items:center;justify-content:flex-end;gap:7px}.ra-header-tools .form-select{min-width:210px;height:40px}.ra-header-tools .btn{min-height:34px;border-radius:5px;font-size:12px;font-weight:650}.ra-legend{display:flex;flex-wrap:wrap;gap:8px}.ra-legend span{display:inline-flex;align-items:center;gap:6px;padding:5px 9px;border:1px solid var(--border);border-radius:5px;color:#45566d;font-size:11px;font-weight:700}.ra-legend i{width:8px;height:8px;border-radius:50%}
    .ra-chart{position:relative;height:350px;padding:18px 20px 8px}.ra-chart canvas,.ra-operation-chart canvas{width:100%!important;height:100%!important}.ra-interpretation{display:flex;align-items:center;justify-content:space-between;gap:18px;margin:0 20px 18px;padding:13px 15px;border-left:4px solid var(--interpretation-color,var(--blue));border-radius:4px;color:#31445e;background:#f7f9fc;font-size:13px}.ra-interpretation strong{color:var(--ink)}.ra-data{display:none;margin:0 20px 20px;overflow:auto}.ra-data.visible{display:block}.ra-data table{width:100%;border-collapse:collapse}.ra-data th,.ra-data td{padding:9px 11px;border:1px solid #e1e6ed;color:#45566d;font-size:12px;text-align:left}.ra-data th{color:#283b55;background:#f4f7fa}
    .ra-operation-tabs{display:flex;gap:7px;padding:12px 16px;overflow:auto;border-bottom:1px solid #e3e8ef}.ra-operation-tabs button{flex:0 0 auto;min-height:36px;padding:7px 13px;border:1px solid #cad3df;border-radius:5px;color:#455b76;background:#fff;font-size:12px;font-weight:700}.ra-operation-tabs button.active{border-color:var(--blue);color:#fff;background:var(--blue)}.ra-operation-layout{display:grid;grid-template-columns:minmax(0,1fr) 370px;min-height:650px}.ra-operation-main{min-width:0;padding:16px}.ra-operation-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));overflow:hidden;border:1px solid var(--border);border-radius:7px}.ra-operation-metrics button,.ra-operation-metrics>div{min-height:78px;padding:12px;border:0;border-right:1px solid var(--border);color:#63748a;background:#fff;text-align:center}.ra-operation-metrics>:last-child{border-right:0}.ra-operation-metrics button.active{box-shadow:inset 0 -4px 0 var(--blue);background:#f7faff}.ra-operation-metrics span{display:block;font-size:11px;font-weight:700}.ra-operation-metrics strong{display:block;margin-top:4px;color:var(--ink);font-size:22px}.ra-operation-chart{position:relative;height:290px;padding:18px 4px 10px}
    .ra-ticket-tools{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 0;border-top:1px solid #e4e9ef}.ra-ticket-filters{display:flex;gap:5px}.ra-ticket-filters button{padding:6px 10px;border:1px solid #ccd5df;border-radius:4px;color:#566980;background:#fff;font-size:11px;font-weight:700}.ra-ticket-filters button.active{border-color:var(--blue);color:var(--blue);background:#f2f7ff}.ra-ticket-tools .form-control{width:min(250px,45%);height:34px;border-radius:5px;font-size:12px}.ra-ticket-list{display:grid;max-height:330px;overflow:auto;border:1px solid #e0e6ed;border-radius:6px}.ra-ticket-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;padding:11px 13px;border:0;border-bottom:1px solid #e8ecf1;color:inherit;background:#fff;text-align:left}.ra-ticket-row:hover,.ra-ticket-row.active{background:#f3f7fd;box-shadow:inset 3px 0 var(--blue)}.ra-ticket-row h5{margin:0 0 3px;color:var(--ink);font-size:13px}.ra-ticket-row p{margin:0;color:#6c7c90;font-size:11px}.ra-badge{display:inline-flex;align-self:center;padding:4px 7px;border-radius:4px;color:#fff;background:#77869a;font-size:10px;font-weight:800;white-space:nowrap}
    .ra-live-panel{min-width:0;padding:18px;border-left:1px solid var(--border);background:#fbfcfd}.ra-live-heading{display:flex;justify-content:space-between;gap:10px;padding-bottom:13px;border-bottom:1px solid var(--border)}.ra-live-heading h4{margin:0;color:var(--ink);font-size:17px}.ra-live-heading small{color:#65768b;font-size:11px}.ra-live-heading small i{display:inline-block;width:8px;height:8px;margin-right:5px;border-radius:50%;background:#10a6a6}.ra-ticket-id{padding:4px 7px;border-radius:4px;color:var(--blue);background:#eaf1fb;font-size:11px;font-weight:700}.ra-empty{padding:40px 20px;color:#738197;text-align:center}.ra-detail h3{margin:18px 0 6px;color:var(--ink);font-size:18px}.ra-detail>p{color:#617289;font-size:12px;line-height:1.55;white-space:pre-wrap}.ra-detail-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin:14px 0}.ra-detail-grid>div{padding:8px;border:1px solid #e0e5eb;border-radius:5px;background:#fff}.ra-detail-grid span{display:block;color:#748298;font-size:9px;font-weight:700;text-transform:uppercase}.ra-detail-grid strong{display:block;margin-top:2px;color:#233953;font-size:11px;overflow-wrap:anywhere}.ra-workflow{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));margin:18px 0}.ra-workflow-step{position:relative;padding-top:24px;color:#8794a6;font-size:9px;font-weight:700;text-align:center}.ra-workflow-step::before{position:absolute;top:8px;right:0;left:0;height:3px;background:#d8dfe7;content:''}.ra-workflow-step:first-child::before{left:50%}.ra-workflow-step:last-child::before{right:50%}.ra-workflow-step i{position:absolute;z-index:1;top:2px;left:50%;width:15px;height:15px;margin-left:-7px;border:3px solid #d8dfe7;border-radius:50%;background:#fff}.ra-workflow-step.done{color:var(--green)}.ra-workflow-step.done::before{background:var(--green)}.ra-workflow-step.done i{border-color:var(--green);background:var(--green)}.ra-workflow-step.current{color:var(--blue)}.ra-workflow-step.current i{border-color:var(--blue)}.ra-detail-actions{display:flex;gap:7px;margin-top:12px}.ra-detail-actions .btn{flex:1 1 auto;min-height:39px;font-size:11px;font-weight:700}
    .ra-alert-list{display:grid;gap:10px;padding:16px 20px 20px}.ra-alert{display:grid;grid-template-columns:34px minmax(0,1fr);gap:11px;align-items:start;width:100%;padding:12px;border:1px solid #e2e7ee;border-left:4px solid var(--alert-color);border-radius:6px;color:inherit;background:#fafbfc;text-align:left}.ra-alert:hover{border-color:var(--alert-color);background:#f4f7fb}.ra-alert-icon{display:grid;width:30px;height:30px;place-items:center;color:var(--alert-color)}.ra-alert h4{margin:0 0 3px;color:var(--ink);font-size:14px}.ra-alert p{margin:0;color:var(--muted);font-size:12px}.role-summary-swal{color:#31445e;text-align:left;line-height:1.55}.role-summary-swal li{margin-bottom:8px}
    @media(max-width:1100px){.ra-kpis{grid-template-columns:repeat(2,minmax(0,1fr))}.ra-operation-layout{grid-template-columns:1fr}.ra-live-panel{border-top:1px solid var(--border);border-left:0}}@media(max-width:650px){.role-analytics{padding:12px}.ra-kpis{grid-template-columns:1fr}.ra-filter>*{width:100%}.ra-filter .form-control,.ra-filter .btn{width:100%}.ra-header,.ra-interpretation{align-items:flex-start;flex-direction:column}.ra-header-tools{justify-content:flex-start;width:100%}.ra-header-tools .form-select{width:100%}.ra-chart{height:290px;padding-inline:10px}.ra-operation-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.ra-operation-metrics>:nth-child(2){border-right:0}.ra-ticket-tools{align-items:stretch;flex-direction:column}.ra-ticket-tools .form-control{width:100%}}
</style>
@endsection

@section('content')
<main class="role-analytics">
    <form class="ra-panel ra-filter" method="GET" action="{{ route('role.analytics') }}"><div><label for="date_from">From</label><input class="form-control" id="date_from" name="date_from" type="date" value="{{ $filters['date_from'] ?? '' }}"></div><div><label for="date_to">To</label><input class="form-control" id="date_to" name="date_to" type="date" value="{{ $filters['date_to'] ?? '' }}"></div><button class="btn btn-primary" type="submit"><i class="fas fa-filter me-1"></i> Apply</button><a class="btn btn-outline-secondary" href="{{ route('role.analytics') }}"><i class="fas fa-rotate-left me-1"></i> Reset</a></form>
    <section class="ra-kpis">@foreach($metrics as $metric)<article class="ra-panel ra-kpi" style="--accent:{{ $metric['color'] }}"><div class="ra-kpi-head"><span class="ra-kpi-label">{{ $metric['label'] }}</span><span class="ra-kpi-icon"><i class="fas {{ $metric['icon'] }}"></i></span></div><div class="ra-kpi-value">{{ number_format($metric['value']) }}</div><div class="ra-kpi-context">{{ $metric['context'] }}</div></article>@endforeach</section>

    <section class="ra-panel">
        <header class="ra-header"><div><h3 id="roleChartTitle">{{ $mode === 'mis' ? 'Reports Trend' : 'Requests Trend' }}</h3><p id="roleChartSubtitle">Historical volume and completed work</p></div><div class="ra-header-tools"><select class="form-select" id="roleChartSelector"><option value="trend">{{ $mode === 'mis' ? 'Report Trends' : 'Request Trends' }}</option><option value="status">Status Distribution</option><option value="priority">Priority Distribution</option></select><div class="ra-legend" id="roleChartLegend"></div><button class="btn btn-outline-secondary" id="roleDataToggle" type="button"><i class="fas fa-table me-1"></i> Data</button><button class="btn btn-outline-secondary" id="roleChartDownload" type="button" title="Download chart"><i class="fas fa-download"></i></button></div></header>
        <div class="ra-chart"><canvas id="roleTrendChart"></canvas></div><div class="ra-interpretation" id="roleInterpretation"><div><strong>System interpretation:</strong> <span id="roleInterpretationText"></span></div><button class="btn btn-sm btn-outline-primary" id="roleExecutiveSummary" type="button"><i class="fas fa-file-lines me-1"></i> Executive Summary</button></div><div class="ra-data" id="roleChartData"></div>
    </section>

    <section class="ra-panel">
        <header class="ra-header"><div><h3>Operations Analytics</h3><p>Select an operation, inspect its trend and tickets, then manage the {{ $mode === 'mis' ? 'MIS task' : 'event approval' }} workflow</p></div><div class="ra-header-tools"><button class="btn btn-outline-primary" id="roleOperationSummary" type="button"><i class="fas fa-file-lines me-1"></i> Summary</button><button class="btn btn-outline-secondary" id="roleOperationDownload" type="button"><i class="fas fa-download"></i></button></div></header>
        <nav class="ra-operation-tabs" id="roleOperationNav" aria-label="Analytics operations"></nav><div class="ra-operation-layout"><div class="ra-operation-main" id="roleOperationMain"></div><aside class="ra-live-panel"><div class="ra-live-heading"><div><h4>Ticket Details</h4><small><i></i> Updating live</small></div><span class="ra-ticket-id" id="roleDetailReference">Select a ticket</span></div><div class="ra-empty" id="roleEmptyDetail"><i class="fas fa-ticket fa-2x mb-2"></i><p>Select a ticket to view its details and workflow.</p></div><div class="ra-detail" id="roleTicketDetail" hidden></div></aside></div>
    </section>

    <section class="ra-panel"><header class="ra-header"><div><h3>Decision Alerts</h3><p>{{ $mode === 'mis' ? 'MIS workload exceptions requiring review' : 'Approval delays and time-sensitive requests requiring review' }}</p></div></header><div class="ra-alert-list">@foreach($decisionAlerts as $index => $alert) @php $alertColor=match($alert['level']){'critical'=>'#d93645','warning'=>'#e99a00','success'=>'#148a58',default=>'#1769e0'};$alertIcon=match($alert['level']){'critical'=>'fa-circle-exclamation','warning'=>'fa-triangle-exclamation','success'=>'fa-circle-check',default=>'fa-circle-info'}; @endphp <button class="ra-alert" style="--alert-color:{{ $alertColor }}" type="button" data-alert-index="{{ $index }}"><span class="ra-alert-icon"><i class="fas {{ $alertIcon }}"></i></span><div><h4>{{ $alert['title'] }}</h4><p>{{ $alert['body'] }}</p></div></button>@endforeach</div></section>
</main>
@endsection

@section('scripts')
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script>
<script>
document.addEventListener('DOMContentLoaded',function(){
const mode=@json($mode),summary=@json($summary),trend=@json($trendStats->values()),statusStats=@json($statusStats->values()),operations=@json($operations->values()),decisionAlerts=@json($decisionAlerts->values());
const completedLabel=mode==='mis'?'Resolved':'Approved',submittedLabel=mode==='mis'?'Reports':'Requests';let mainChart=null,operationChart=null,activeOperationIndex=0,activeTicketId=null,ticketFilter='all',activeOperationMetric='submitted';
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'})[character]);const labelize=value=>String(value||'Not set').replaceAll('_',' ').replace(/\b\w/g,character=>character.toUpperCase());
const allTickets=operations.flatMap(operation=>operation.tickets);const groupTickets=field=>Object.entries(allTickets.reduce((groups,ticket)=>{const key=labelize(ticket[field]);groups[key]=(groups[key]||0)+1;return groups},{})).map(([label,count])=>({label,count}));const priorityStats=groupTickets('priority');
function chartConfig(type){if(type==='status'||type==='priority'){const items=type==='status'?statusStats:priorityStats;return{type:'doughnut',title:type==='status'?'Status Distribution':'Priority Distribution',subtitle:type==='status'?'Current workload by status':'Current workload by assigned priority',labels:items.map(item=>item.label),datasets:[{label:'Records',data:items.map(item=>item.count),backgroundColor:['#1769e0','#148a58','#e99a00','#d93645','#6f42c1','#77869a'],borderColor:'#fff',borderWidth:2}],rows:items.map(item=>[item.label,item.count])}}return{type:'line',title:mode==='mis'?'Reports Trend':'Requests Trend',subtitle:'Historical volume and completed work',labels:trend.map(item=>item.label),datasets:[{label:submittedLabel,data:trend.map(item=>item.total),borderColor:'#1769e0',backgroundColor:'rgba(23,105,224,.13)',fill:true,tension:.35},{label:completedLabel,data:trend.map(item=>item.completed),borderColor:'#148a58',backgroundColor:'rgba(20,138,88,.08)',tension:.35}],rows:trend.map(item=>[item.label,item.total,item.completed])}}
function renderMainChart(type='trend'){const config=chartConfig(type);document.getElementById('roleChartTitle').textContent=config.title;document.getElementById('roleChartSubtitle').textContent=config.subtitle;document.getElementById('roleChartLegend').innerHTML=config.datasets.map((dataset,index)=>`<span><i style="background:${Array.isArray(dataset.backgroundColor)?dataset.backgroundColor[index]:dataset.borderColor}"></i>${escapeHtml(dataset.label)}</span>`).join('');mainChart?.destroy();mainChart=new Chart(document.getElementById('roleTrendChart'),{type:config.type,data:{labels:config.labels,datasets:config.datasets},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:config.type==='line'?{y:{beginAtZero:true,ticks:{precision:0}}}:{}}});const headings=type==='trend'?['Month',submittedLabel,completedLabel]:[type==='status'?'Status':'Priority','Records'];document.getElementById('roleChartData').innerHTML=`<table><thead><tr>${headings.map(item=>`<th>${escapeHtml(item)}</th>`).join('')}</tr></thead><tbody>${config.rows.map(row=>`<tr>${row.map(item=>`<td>${escapeHtml(item)}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function renderInterpretation(){const early=trend.slice(0,3).reduce((sum,item)=>sum+item.total,0)/3,recent=trend.slice(3).reduce((sum,item)=>sum+item.total,0)/3,delta=recent-early,total=trend.reduce((sum,item)=>sum+item.total,0),box=document.getElementById('roleInterpretation');let message='There is not enough activity in this period to identify a trend.';box.style.setProperty('--interpretation-color','#66758a');if(total&&delta>0){message=`Recent ${submittedLabel.toLowerCase()} volume increased by ${Math.abs(delta).toFixed(1)} per month compared with the earlier period. Review workload and capacity before demand rises further.`;box.style.setProperty('--interpretation-color','#d93645')}else if(total&&delta<0){message=`Recent ${submittedLabel.toLowerCase()} volume decreased by ${Math.abs(delta).toFixed(1)} per month. Continue the current workflow and monitor unresolved work.`;box.style.setProperty('--interpretation-color','#148a58')}else if(total){message=`${submittedLabel} volume is stable. Focus decisions on open, urgent, and aging records.`;box.style.setProperty('--interpretation-color','#1769e0')}document.getElementById('roleInterpretationText').textContent=message}
function showExecutiveSummary(){Swal.fire({title:summary.title,width:760,html:`<div class="role-summary-swal"><p><strong>Scope:</strong> ${escapeHtml(summary.scope)}</p><ol>${summary.items.map(item=>`<li>${escapeHtml(item)}</li>`).join('')}</ol><p><strong>Recommended decision:</strong> ${escapeHtml(summary.decision)}</p></div>`,confirmButtonText:'Close',confirmButtonColor:'#1769e0'})}
function renderOperationNavigation(){const nav=document.getElementById('roleOperationNav');if(!operations.length){nav.innerHTML='<div class="ra-empty">No operations available for this period.</div>';return}nav.innerHTML=operations.map((operation,index)=>`<button type="button" class="${index===activeOperationIndex?'active':''}" data-operation-index="${index}">${escapeHtml(operation.name)} (${operation.stats.total})</button>`).join('');nav.querySelectorAll('[data-operation-index]').forEach(button=>button.addEventListener('click',function(){activeOperationIndex=Number(this.dataset.operationIndex);activeTicketId=null;ticketFilter='all';activeOperationMetric='submitted';renderOperationNavigation();renderOperation()}))}
function renderOperation(){const main=document.getElementById('roleOperationMain');if(!operations.length){main.innerHTML='<div class="ra-empty">No matching tickets are available.</div>';renderTicketDetail(null);return}const operation=operations[activeOperationIndex];activeTicketId??=operation.tickets[0]?.id??null;main.innerHTML=`<div class="ra-operation-metrics"><button class="${activeOperationMetric==='submitted'?'active':''}" data-operation-metric="submitted" type="button"><span>${submittedLabel}</span><strong>${operation.stats.total}</strong></button><button class="${activeOperationMetric==='completed'?'active':''}" data-operation-metric="completed" type="button"><span>${completedLabel}</span><strong>${operation.stats.completed}</strong></button><div><span>${mode==='mis'?'High Priority':'Rejected'}</span><strong>${operation.stats.urgent}</strong></div><div><span>Open</span><strong>${operation.stats.open}</strong></div></div><div class="ra-operation-chart"><canvas id="roleOperationChart"></canvas></div><div class="ra-ticket-tools"><div class="ra-ticket-filters"><button class="${ticketFilter==='all'?'active':''}" data-ticket-filter="all" type="button">All</button><button class="${ticketFilter==='open'?'active':''}" data-ticket-filter="open" type="button">Open</button><button class="${ticketFilter==='completed'?'active':''}" data-ticket-filter="completed" type="button">${completedLabel}</button></div><input class="form-control" id="roleTicketSearch" type="search" placeholder="Search tickets..."></div><div class="ra-ticket-list" id="roleTicketList"></div>`;const metricKey=activeOperationMetric==='completed'?'completed':'total',metricLabel=activeOperationMetric==='completed'?completedLabel:`${submittedLabel} submitted`,metricColor=activeOperationMetric==='completed'?'#148a58':'#1769e0';operationChart?.destroy();operationChart=new Chart(document.getElementById('roleOperationChart'),{type:'line',data:{labels:operation.trend.map(item=>item.label),datasets:[{label:`${operation.name} - ${metricLabel}`,data:operation.trend.map(item=>item[metricKey]),borderColor:metricColor,backgroundColor:activeOperationMetric==='completed'?'rgba(20,138,88,.13)':'rgba(23,105,224,.13)',fill:true,tension:.35}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}},scales:{y:{beginAtZero:true,ticks:{precision:0}}}}});main.querySelectorAll('[data-operation-metric]').forEach(button=>button.addEventListener('click',function(){activeOperationMetric=this.dataset.operationMetric;renderOperation()}));main.querySelectorAll('[data-ticket-filter]').forEach(button=>button.addEventListener('click',function(){ticketFilter=this.dataset.ticketFilter;renderOperation()}));document.getElementById('roleTicketSearch').addEventListener('input',()=>renderTicketList(operation));renderTicketList(operation)}
function renderTicketList(operation){const search=document.getElementById('roleTicketSearch')?.value.trim().toLowerCase()||'',isComplete=ticket=>String(ticket.status).toLowerCase()===String(completedLabel).toLowerCase(),tickets=operation.tickets.filter(ticket=>(ticketFilter==='all'||(ticketFilter==='completed'&&isComplete(ticket))||(ticketFilter==='open'&&!isComplete(ticket)))&&(!search||`${ticket.reference} ${ticket.title} ${ticket.location} ${ticket.assignee}`.toLowerCase().includes(search)));if(tickets.length&&!tickets.some(ticket=>Number(ticket.id)===Number(activeTicketId)))activeTicketId=tickets[0].id;const list=document.getElementById('roleTicketList');list.innerHTML=tickets.length?tickets.map(ticket=>`<button class="ra-ticket-row ${Number(ticket.id)===Number(activeTicketId)?'active':''}" data-ticket-id="${ticket.id}" type="button"><span><h5>${escapeHtml(ticket.title)}</h5><p>${escapeHtml(ticket.reference)} | ${escapeHtml(ticket.location)} | ${escapeHtml(ticket.assignee)}</p></span><span class="ra-badge">${escapeHtml(ticket.status)}</span></button>`).join(''):'<div class="ra-empty">No matching tickets.</div>';list.querySelectorAll('[data-ticket-id]').forEach(button=>button.addEventListener('click',function(){activeTicketId=Number(this.dataset.ticketId);renderTicketList(operation)}));renderTicketDetail(tickets.find(ticket=>Number(ticket.id)===Number(activeTicketId))||null)}
function renderTicketDetail(ticket){const detail=document.getElementById('roleTicketDetail'),empty=document.getElementById('roleEmptyDetail'),reference=document.getElementById('roleDetailReference');if(!ticket){detail.hidden=true;empty.hidden=false;reference.textContent='Select a ticket';return}empty.hidden=true;detail.hidden=false;reference.textContent=ticket.reference;const status=String(ticket.status).toLowerCase(),steps=mode==='mis'?['Pending','Assigned','In Progress','Resolved']:['Submitted','In Review','Decision','Complete'];let current=mode==='mis'?({'pending':0,'assigned':1,'in progress':2,'resolved':3}[status]??1):(status==='pending'?1:3);detail.innerHTML=`<h3>${escapeHtml(ticket.title)}</h3><p>${escapeHtml(ticket.description)}</p><div class="ra-detail-grid"><div><span>Status</span><strong>${escapeHtml(ticket.status)}</strong></div><div><span>Location</span><strong>${escapeHtml(ticket.location)}</strong></div><div><span>Priority</span><strong>${escapeHtml(labelize(ticket.priority))}</strong></div><div><span>${mode==='mis'?'Assigned To':'Current Approver'}</span><strong>${escapeHtml(ticket.assignee)}</strong></div><div><span>Submitted</span><strong>${escapeHtml(ticket.created_at)}</strong></div><div><span>${mode==='mis'?'Reported Count':'Requester'}</span><strong>${escapeHtml(mode==='mis'?ticket.report_count:ticket.requester)}</strong></div></div><div class="ra-workflow">${steps.map((step,index)=>`<span class="ra-workflow-step ${index<current?'done':index===current?'current':''}"><i></i>${step}</span>`).join('')}</div><div class="ra-detail-actions"><a class="btn btn-primary" href="${escapeHtml(ticket.url)}"><i class="fas fa-arrow-up-right-from-square me-1"></i> Open ${mode==='mis'?'MIS Task':'Event Request'}</a></div>`}
function downloadChart(chart,name){if(!chart)return;const link=document.createElement('a');link.download=`${name}.png`;link.href=chart.toBase64Image();link.click()}
document.getElementById('roleChartSelector').addEventListener('change',event=>renderMainChart(event.target.value));document.getElementById('roleDataToggle').addEventListener('click',()=>document.getElementById('roleChartData').classList.toggle('visible'));document.getElementById('roleChartDownload').addEventListener('click',()=>downloadChart(mainChart,'role-analytics-chart'));document.getElementById('roleOperationDownload').addEventListener('click',()=>downloadChart(operationChart,'operation-analytics-chart'));document.getElementById('roleExecutiveSummary').addEventListener('click',showExecutiveSummary);document.getElementById('roleOperationSummary').addEventListener('click',function(){const operation=operations[activeOperationIndex];if(!operation)return;Swal.fire({title:`${escapeHtml(operation.name)} Summary`,html:`<div class="role-summary-swal"><p><strong>${operation.stats.total}</strong> total, <strong>${operation.stats.open}</strong> open, and <strong>${operation.stats.completed}</strong> ${completedLabel.toLowerCase()}.</p><p>${escapeHtml(summary.decision)}</p></div>`,confirmButtonColor:'#1769e0'})});document.querySelectorAll('[data-alert-index]').forEach(button=>button.addEventListener('click',function(){const alert=decisionAlerts[Number(this.dataset.alertIndex)],records=alert.tickets.length?`<div><strong>Related records</strong>${alert.tickets.map(ticket=>`<a href="${escapeHtml(ticket.url)}" style="display:block;margin-top:8px;padding:8px;border:1px solid #dce2ea;border-radius:5px;text-decoration:none"><b>${escapeHtml(ticket.reference)}</b> - ${escapeHtml(ticket.title)}<br><small>${escapeHtml(ticket.status)} - ${escapeHtml(ticket.owner)}</small></a>`).join('')}</div>`:'';Swal.fire({icon:alert.level==='critical'?'error':alert.level,title:alert.title,width:700,html:`<div class="role-summary-swal"><p>${escapeHtml(alert.body)}</p><p><strong>Why it matters:</strong> ${escapeHtml(alert.why)}</p><p><strong>Recommended action:</strong> ${escapeHtml(alert.impact)}</p>${records}</div>`,confirmButtonColor:'#1769e0'})}));renderMainChart();renderInterpretation();renderOperationNavigation();renderOperation()});
</script>
@endsection
