@php
    $hazardItems = $reports->filter(fn ($report) => (bool) $report->is_safety_hazard);
    $openHazardItems = $hazardItems->filter(fn ($report) => strtolower((string) $report->status) !== 'resolved');
    $hazardAvgAge = $openHazardItems->count() > 0 ? round($openHazardItems->avg(fn ($report) => $report->created_at ? $report->created_at->diffInHours(now()) / 24 : 0), 1) : 0;
    $mostActiveLocation = $locationStats->sortByDesc('total')->first();
@endphp

<article class="dss-report" id="dssExecutiveReportContent">
    <header class="dss-report-cover">
        <img src="{{ asset('Campfix/Images/logo.png') }}" alt="CampFix logo">
        <div><span>CampFix Decision Support System</span><h1>Executive Maintenance Analytics Report</h1><p>{{ $executiveSummary['period'] }}</p></div>
        <dl><div><dt>Generated</dt><dd>{{ now()->format('M d, Y h:i A') }}</dd></div><div><dt>Generated By</dt><dd>{{ auth()->user()->name ?? 'CampFix Administrator' }}</dd></div><div><dt>Priority</dt><dd>{{ $priorityLevel }}</dd></div></dl>
    </header>

    <section class="dss-report-section">
        <h2>1. Executive Management Summary</h2>
        @if($totalReports > 0)
            <p>During the selected period, CampFix processed <strong>{{ number_format($totalReports) }} maintenance reports across {{ number_format($locationStats->count()) }} locations</strong>. {{ number_format($openReports) }} reports remain open while {{ number_format($resolvedReports) }} have been resolved.</p>
            <p>The open workload consists of {{ number_format($pendingReports) }} pending and {{ number_format($assignedReports) }} assigned reports. @if($estimatedBacklogDays !== null) Based on the previous 30 days of completions, clearing the current backlog may require approximately <strong>{{ number_format($estimatedBacklogDays) }} working days</strong> if capacity remains unchanged. @else Backlog clearance cannot yet be estimated because no recent completion throughput is available. @endif</p>
            @if($topCategory)<p><strong>{{ $topCategory['category'] }}</strong> is the leading category with {{ number_format($topCategory['count']) }} reports and a {{ strtolower($topCategory['trend_direction']) }} monthly trend. @if($topLocation)<strong>{{ $topLocation['location'] }}</strong> carries the highest operational risk score of {{ $topLocation['risk_score'] }}, with {{ $topLocation['open'] }} unresolved and {{ $topLocation['hazards'] }} hazard-related reports. @endif</p>@endif
            <p>Safety-related reports account for <strong>{{ number_format($hazardReports) }} cases</strong>. The overall DSS risk index is <strong>{{ $riskIndex }}/100</strong>, resulting in a <strong>{{ $priorityLevel }}</strong> management priority.</p>
            @if($executiveSummary['top_recurring_issue'])<p>The leading repeated repair is <strong>{{ $executiveSummary['top_recurring_issue']['issue'] }} in {{ $executiveSummary['top_recurring_issue']['location'] }}</strong>, with {{ number_format($executiveSummary['top_recurring_issue']['repair_cycles']) }} completed repair cycle(s), {{ number_format($executiveSummary['top_recurring_issue']['count']) }} report(s), and PHP {{ number_format($executiveSummary['top_recurring_issue']['cost'], 2) }} in recorded repair cost. Management should compare projected repair spending with a replacement quotation before approving another repair for the same issue in the same location.</p>@endif
        @else
            <p>No reports match the selected filters. Management conclusions should be deferred until a broader date range or location scope is selected.</p>
        @endif
    </section>

    <section class="dss-report-section">
        <h2>2. Executive KPI Scorecard</h2>
        <div class="dss-scorecards">
            @foreach([
                ['Total Reports', number_format($totalReports), 'All selected records'],
                ['Open Reports', number_format($openReports), number_format($avgReportAgeDays, 1).' avg days old'],
                ['Resolved', number_format($resolvedReports), 'Completed reports'],
                ['Hazards', number_format($hazardReports), number_format($openHazardItems->count()).' currently open'],
                ['Risk Index', $riskIndex.'/100', $priorityLevel.' priority'],
                ['Trend', $trendDirection, number_format(abs($monthlyChangePercent), 1).'% monthly change'],
            ] as $score)
                <div><span>{{ $score[0] }}</span><strong>{{ $score[1] }}</strong><small>{{ $score[2] }}</small></div>
            @endforeach
        </div>
    </section>

    <section class="dss-report-section">
        <h2>3. System-Generated Insights</h2>
        <ul class="dss-insights">@forelse($aiInsights as $insight)<li>{{ $insight }}</li>@empty<li>Insufficient data for automated insight generation.</li>@endforelse</ul>
    </section>

    <section class="dss-report-section dss-page-break">
        <h2>4. Report Status Analysis</h2>
        <table class="dss-report-table"><thead><tr><th>Status</th><th>Reports</th><th>Oldest</th><th>Priority</th></tr></thead><tbody>@foreach($statusStats as $status)<tr><td>{{ $status['status'] }}</td><td>{{ $status['count'] }}</td><td>{{ $status['oldest_days'] }} days</td><td>{{ $status['priority'] }}</td></tr>@endforeach</tbody></table>
    </section>

    <section class="dss-report-section">
        <h2>5. Category Analysis</h2>
        <table class="dss-report-table"><thead><tr><th>Category</th><th>Reports</th><th>Hazards</th><th>Trend</th></tr></thead><tbody>@foreach($categoryStats as $category)<tr><td>{{ $category['category'] }}</td><td>{{ $category['count'] }}</td><td>{{ $category['hazards'] }}</td><td>{{ $category['trend_direction'] }} ({{ number_format($category['trend_percent'], 1) }}%)</td></tr>@endforeach</tbody></table>
    </section>

    <section class="dss-report-section">
        <h2>6. Location Risk Analysis</h2>
        <p>Highest risk: <strong>{{ $topLocation['location'] ?? 'N/A' }}</strong>. Most active: <strong>{{ $mostActiveLocation['location'] ?? 'N/A' }}</strong>.</p>
        <table class="dss-report-table"><thead><tr><th>Location</th><th>Reports</th><th>Open</th><th>Closed</th><th>Hazards</th><th>Risk</th><th>Priority</th></tr></thead><tbody>@foreach($locationStats->take(15) as $location)<tr><td>{{ $location['location'] }}</td><td>{{ $location['total'] }}</td><td>{{ $location['open'] }}</td><td>{{ $location['resolved'] }}</td><td>{{ $location['hazards'] }}</td><td>{{ $location['risk_score'] }}</td><td>{{ $location['risk_score'] >= 12 ? 'High' : ($location['risk_score'] >= 6 ? 'Medium' : 'Low') }}</td></tr>@endforeach</tbody></table>
    </section>

    <section class="dss-report-section dss-page-break">
        <h2>7. Hazard and Financial Analysis</h2>
        <table class="dss-report-table"><thead><tr><th>Hazard Level</th><th>Reports</th><th>Open</th><th>Avg Age</th></tr></thead><tbody><tr><td>Safety Hazard</td><td>{{ $hazardReports }}</td><td>{{ $openHazardItems->count() }}</td><td>{{ number_format($hazardAvgAge, 1) }} days</td></tr></tbody></table>
    </section>

    <section class="dss-report-section">
        <h2>8. Staff Performance</h2>
        <table class="dss-report-table"><thead><tr><th>Staff</th><th>Assigned</th><th>Resolved</th><th>Avg Hours</th><th>SLA</th><th>Efficiency</th></tr></thead><tbody>@forelse($staffStats as $staff)<tr><td>{{ $staff['staff'] }}</td><td>{{ $staff['assigned'] }}</td><td>{{ $staff['resolved'] }}</td><td>{{ $staff['avg_hours'] !== null ? number_format($staff['avg_hours'], 1) : 'N/A' }}</td><td>{{ $staff['sla'] !== null ? number_format($staff['sla'], 1).'%' : 'N/A' }}</td><td>{{ number_format($staff['efficiency'], 1) }}%</td></tr>@empty<tr><td colspan="6">No assignment performance data is available.</td></tr>@endforelse</tbody></table>
    </section>

    <section class="dss-report-section dss-page-break">
        <h2>Appendix A. Report Evidence</h2>
        <table class="dss-report-table"><thead><tr><th>Date</th><th>Report</th><th>Location</th><th>Category</th><th>Status</th><th>Priority</th><th>Assigned</th></tr></thead><tbody>@foreach($reports->sortByDesc('created_at')->take(50) as $report)<tr><td>{{ optional($report->created_at)->format('m/d/Y') }}</td><td>{{ $report->title ?: 'Untitled report' }}</td><td>{{ $report->location ?: 'N/A' }}</td><td>{{ optional($report->category)->name ?: 'Uncategorized' }}</td><td>{{ $report->status }}</td><td>{{ $report->severity ?: 'N/A' }}</td><td>{{ optional($report->assignedTo)->name ?: 'Unassigned' }}</td></tr>@endforeach</tbody></table>
    </section>
</article>
