@php
    $fromDate = ! empty($filters['date_from']) ? \Carbon\Carbon::parse($filters['date_from'])->format('M d, Y') : null;
    $toDate = ! empty($filters['date_to']) ? \Carbon\Carbon::parse($filters['date_to'])->format('M d, Y') : null;
    $reportPeriod = $fromDate && $toDate
        ? $fromDate.' to '.$toDate
        : ($fromDate ? 'From '.$fromDate : ($toDate ? 'Through '.$toDate : 'All available records'));
    $totalRecords = (int) $operations->sum(fn ($operation) => $operation['stats']['total']);
    $completedRecords = (int) $operations->sum(fn ($operation) => $operation['stats']['completed']);
    $recordLabel = $mode === 'mis' ? 'Technology/Internet reports' : 'event requests';
    $completionLabel = $mode === 'mis' ? 'resolved' : 'approved';
@endphp

<article class="role-executive-report">
    <header class="rer-cover">
        <img src="{{ asset('Campfix/Images/STI-Academic-Seal-One-Color_400.png') }}" alt="STI College seal">
        <div class="rer-cover-title">
            <span>CampFix Decision Support System</span>
            <h1>{{ $summary['title'] }}</h1>
            <p>{{ $reportPeriod }}</p>
        </div>
        <img src="{{ asset('Campfix/Images/logo.png') }}" alt="CampFix logo">
        <dl>
            <div><dt>Generated</dt><dd>{{ now()->format('M d, Y h:i A') }}</dd></div>
            <div><dt>Generated by</dt><dd>{{ auth()->user()->name ?? 'CampFix User' }}</dd></div>
            <div><dt>Role</dt><dd>{{ auth()->user()->role_display_name ?? $pageTitle }}</dd></div>
            <div><dt>Scope</dt><dd>{{ $summary['scope'] }}</dd></div>
        </dl>
    </header>

    <section class="rer-section">
        <h2>1. Executive Management Summary</h2>
        <p>During the selected period, this dashboard reviewed <strong>{{ number_format($totalRecords) }} {{ $recordLabel }}</strong> within the responsibilities of the {{ auth()->user()->role_display_name ?? $pageTitle }} role. The analysis is limited to records that this role is authorized to monitor or act upon.</p>
        @foreach($summary['items'] as $item)
            <p>{{ $item }}</p>
        @endforeach
        <p>{{ number_format($completedRecords) }} record(s) were {{ $completionLabel }} in the selected scope. Management should compare this completed workload with the remaining open records when assigning capacity and setting response priorities.</p>
    </section>

    <section class="rer-section">
        <h2>2. Executive Scorecard</h2>
        <div class="rer-scorecards">
            @foreach($metrics as $metric)
                <div>
                    <span>{{ $metric['label'] }}</span>
                    <strong>{{ number_format($metric['value']) }}</strong>
                    <small>{{ $metric['context'] }}</small>
                </div>
            @endforeach
        </div>
    </section>

    <section class="rer-section rer-chart-section">
        <h2>3. Workload Trend</h2>
        <p>The chart below presents historical workload volume and completed outcomes. It should be read together with the scorecard and decision alerts to identify rising demand, unfinished work, and capacity requirements.</p>
        <figure><img data-role-report-chart alt="Role analytics workload trend"></figure>
    </section>

    <section class="rer-section">
        <h2>4. Status Analysis</h2>
        @if($statusStats->isNotEmpty())
            <p>The current workload is distributed across {{ number_format($statusStats->count()) }} status group(s). The largest group is <strong>{{ $statusStats->first()['label'] }}</strong>, containing {{ number_format($statusStats->first()['count']) }} record(s), and should be reviewed against the expected workflow stage.</p>
            <table class="rer-table"><thead><tr><th>Status</th><th>Records</th><th>Share</th></tr></thead><tbody>
                @foreach($statusStats as $status)
                    <tr><td>{{ $status['label'] }}</td><td>{{ number_format($status['count']) }}</td><td>{{ $totalRecords > 0 ? number_format(($status['count'] / $totalRecords) * 100, 1).'%' : '0.0%' }}</td></tr>
                @endforeach
            </tbody></table>
        @else
            <p>No status data is available for the selected period. A management conclusion should be deferred until matching records are available.</p>
        @endif
    </section>

    <section class="rer-section">
        <h2>5. Operations Analysis</h2>
        @forelse($operations as $operation)
            <p><strong>{{ $operation['name'] }}</strong> contains {{ number_format($operation['stats']['total']) }} record(s). {{ number_format($operation['stats']['open']) }} remain open, {{ number_format($operation['stats']['completed']) }} are {{ $completionLabel }}, and {{ number_format($operation['stats']['urgent']) }} are classified as {{ $mode === 'mis' ? 'high-priority exceptions' : 'rejected outcomes' }}.</p>
        @empty
            <p>No operational records match the selected period.</p>
        @endforelse
    </section>

    <section class="rer-section">
        <h2>6. Decision Alerts and Recommended Action</h2>
        @foreach($decisionAlerts as $alert)
            <div class="rer-recommendation">
                <strong>{{ $alert['title'] }}.</strong>
                <p>{{ $alert['body'] }} {{ $alert['why'] }} {{ $alert['impact'] }}</p>
            </div>
        @endforeach
        <div class="rer-decision"><strong>Recommended management decision:</strong> {{ $summary['decision'] }}</div>
    </section>

    <footer class="rer-document-footer">
        <img src="{{ asset('Campfix/Images/STI-Academic-Seal-One-Color_400.png') }}" alt="STI College seal">
        <p><strong>STI College Novaliches</strong><br>CampFix Decision Support System &middot; Role-scoped executive analytics<br>This system-generated report is intended for authorized institutional use.</p>
    </footer>
</article>
